server:
  port: 99
spring:
  application:
    name: cloud-gateway
    #加载环境配置，路由配置，跨域配置
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  profiles:
    active: route,cors
  redis:
    host: 192.168.38.128
    port: 6379
    database: 0
  resources:
    static-locations: file:d:/pic/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8764/eureka/
---
spring:
  cloud:
    gateway:
      routes:
        #gateway网关的唯一标识       #################配置user
        - id: orderService
          #后端微服务的名称，和注册中心的名称一致
          uri: lb://SERVICE-ORDER
          #断言策略，根据path断言
          predicates:
            - Path=/order/**
          #去除前缀
          filters:
            - StripPrefix=0
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@hostAddrKeyResolver}'
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 3
          #gateway网关的唯一标识          #################配置order
        - id: userService
          #后端微服务的名称，和注册中心的名称一致
          uri: lb://SERVICE-USER
          #断言策略，根据path断言
          predicates:
            - Path=/user/**
          #去除前缀
          filters:
            - StripPrefix=0
        #################配置配置中心
        - id: configServer
          #后端微服务的名称，和注册中心的名称一致
          uri: lb://CONFIG-SERVER
          #断言策略，根据path断言
          predicates:
            - Path=/config/**
          #去除前缀
          filters:
            - StripPrefix=0
  profiles: route

---
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            # 允许携带认证信息
            # 允许跨域的源(网站域名/ip)，设置*为全部
            # 允许跨域请求里的head字段，设置*为全部
            # 允许跨域的method， 默认为GET和OPTIONS，设置*为全部
            # 跨域允许的有效期
            allow-credentials: true
            allowed-origins: "*"
            #- "http://localhost:8080"
            #- "http://localhost:13010"
            allowed-headers: "*"
            allowed-methods:
              - OPTIONS
              - GET
              - POST
            max-age: 3600
  profiles: cors


